[package]
name = "scte35"
authors = ["Rafael Caricio <rafael@caricio.com>"]
description = "SCTE-35 2022 parser and library"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
base64 = { version = "0.13", default-features = false, features = ["alloc"] }
bitstream-io = "1.3"
deku = { version = "0.13", default-features = false, features = ["alloc"] }
crc = "3.0"
thiserror = "1"
serde = { version = "1", features = ["derive"], optional = true }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
anyhow = "1"
ascii = "1"

[dev-dependencies]
serde_json = "1"
assert-json-diff = "2"
hexlit = "0.5"
