[package]
name = "scte35"
authors = ["Rafael Caricio <rafael@caricio.com>"]
description = "SCTE-35 2022 parser and library"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
base64 = "0.13"
bitstream-io = "1.3"
crc = "3.0"
thiserror = "1"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1"
anyhow = "1"
assert-json-diff = "2"
