[package]
name = "scte35-parsing"
version = "0.1.0"
edition = "2021"
publish = ["crates-io"]

[features]
default = ["crc-validation", "serde"]
crc-validation = ["crc"]
cli = ["base64", "crc-validation"]
serde = ["dep:serde", "dep:serde_json", "base64"]

[dependencies]
crc = { version = "3.0", optional = true }
base64 = { version = "0.22.1", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
base64 = "0.22.1"
serde_json = "1.0"

[[bin]]
name = "scte35-parsing"
required-features = ["cli"]
