[package]
name = "scte35-parsing"
version = "0.1.0"
edition = "2021"
publish = ["crates-io"]

[features]
default = ["crc-validation"]
crc-validation = ["crc"]
cli = ["base64", "crc-validation"]

[dependencies]
crc = { version = "3.0", optional = true }
base64 = { version = "0.22.1", optional = true }

[dev-dependencies]
base64 = "0.22.1"

[[bin]]
name = "scte35-parsing"
required-features = ["cli"]
