name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.rust }}-
          ${{ runner.os }}-cargo-

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Clippy (all warnings as errors)
      run: cargo clippy --tests -- -D clippy::all

    - name: Build (default features)
      run: cargo build --verbose

    - name: Test (default features)
      run: cargo test --verbose

    - name: Build release
      run: cargo build --release

    - name: Generate documentation
      run: cargo doc --no-deps --verbose

  feature-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - name: "No features"
            flags: "--no-default-features"
          - name: "Only CRC validation"
            flags: "--features crc-validation --no-default-features"
          - name: "Only serde"
            flags: "--features serde --no-default-features"
          - name: "Only CLI"
            flags: "--features cli --no-default-features"
          - name: "CRC + serde"
            flags: "--features \"crc-validation,serde\" --no-default-features"
          - name: "CRC + CLI"
            flags: "--features \"crc-validation,cli\" --no-default-features"
          - name: "serde + CLI"
            flags: "--features \"serde,cli\" --no-default-features"
          - name: "All features"
            flags: "--all-features"
          - name: "Default features"
            flags: ""

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-features-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build (${{ matrix.features.name }})
      run: cargo build --verbose ${{ matrix.features.flags }}

    - name: Test (${{ matrix.features.name }})
      run: cargo test --verbose ${{ matrix.features.flags }}

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-coverage-${{ hashFiles('**/Cargo.lock') }}

    - name: Install cargo-tarpaulin
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: latest

    - name: Generate code coverage
      run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true